name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  macos:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Download Updater package
      uses: dawidd6/action-download-artifact@v24
      with:
        workflow: build.yml
        branch: master
        name_is_regexp: true
        name: msi_143_[x64|arm64]
        merge_multiple: true
        repo: open-eid/updater
    - name: Download DigiDoc4 package
      uses: dawidd6/action-download-artifact@v24
      with:
        workflow: build.yml
        branch: appx
        name_is_regexp: true
        name: msi_143_[x64|arm64]
        merge_multiple: true
        repo: open-eid/DigiDoc4-Client
    - name: Download Web-eID packages
      uses: dawidd6/action-download-artifact@v24
      with:
        workflow: cmake-windows.yml
        branch: main
        name_is_regexp: true
        name: web-eid-app-windows-[0-9]*
        merge_multiple: true
        repo: web-eid/web-eid-app
    - name: Cache Open-EID and WIX
      id: cache-open-eid
      uses: actions/cache@v5
      with:
        path: |
          Open-EID.zip
          ~/.dotnet/tools
          ~/.wix
        key: ${{ runner.os }}-open-eid-wix-7.0.0
    - name: Install dependencies
      if: steps.cache-open-eid.outputs.cache-hit != 'true'
      run: |
        dotnet tool install --global wix --version 7.0.0
        wix eula accept wix7
        wix extension -g add WixToolset.UI.wixext/7.0.0
        wix extension -g add WixToolset.Util.wixext/7.0.0
        wix extension -g add WixToolset.BootstrapperApplications.wixext/7.0.0
        curl -O -L https://installer.id.ee/media/win/Open-EID.zip
    - name: Build
      env:
        BUILD_NUBMER: ${{ github.run_number }}
        VER_SUFFIX: .GITHUB
      run: |
        mv arm64\src\app\RelWithDebInfo\*.arm64.msi .
        mv x64\src\app\RelWithDebInfo\*.x64.msi .
        unzip --% Open-EID.zip -x 'Digidoc*' 'web-eid*'
        pwsh build.ps1
    - name: Archive artifacts
      uses: actions/upload-artifact@v7
      with:
        name: windows
        path: Open-EID-*.exe